# -*- coding: utf-8 -*-
"""1.Data Description.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZLNjeiXK4AwW9uYHHrbr9AzqPFsBWUm
"""

# importing libraries
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('/content/sample_data/pm-data set.csv')
print(df.head(20))

df.info()

df.isnull().sum()

df.describe()